[versions]
voldeloom = "2.4-SNAPSHOT"
minecraft = "1.5.2"
forge = "1.5.2-7.8.1.738"
jsr305 = "3.0.2"

[plugins]
voldeloom = { id = "agency.highlysuspect.voldeloom", version.ref = "voldeloom" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }